name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
            cd /home/dev-vue-rss-reader/htdocs/rss-reader.dev-vue.com
            git pull
            php artisan migrate --force --no-interaction
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan cache:clear
